services:
  db:
    image: postgres:15
    container_name: colalink-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
#  pgadmin: â‰¤ Com esse bloco consigo criar um sgbd pelo navegador
#    image: dpage/pgadmin4
#    container_name: colalink-pgadmin
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#    ports:
#      - "8888:80"
volumes:
  postgres_data: